import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Conact from '../components/Conact'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import Projects from '../components/Projects'
import Skills from '../components/Skills'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Yesh-Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
       <Navbar />
       <Main />
       <About />
       <Skills />
       <Projects/>
       <Conact />
    </div>
  )
}
